var srcIndex = JSON.parse('{\
"adler":["",[],["algo.rs","lib.rs"]],\
"bit_field":["",[],["lib.rs"]],\
"bitflags":["",[],["lib.rs"]],\
"bytemuck":["",[],["allocation.rs","anybitpattern.rs","checked.rs","contiguous.rs","internal.rs","lib.rs","no_uninit.rs","offset_of.rs","pod.rs","pod_in_option.rs","transparent.rs","zeroable.rs","zeroable_in_option.rs"]],\
"byteorder":["",[],["io.rs","lib.rs"]],\
"cfg_if":["",[],["lib.rs"]],\
"color_quant":["",[],["lib.rs","math.rs"]],\
"crc32fast":["",[["specialized",[],["mod.rs","pclmulqdq.rs"]]],["baseline.rs","combine.rs","lib.rs","table.rs"]],\
"crossbeam_channel":["",[["flavors",[],["array.rs","at.rs","list.rs","mod.rs","never.rs","tick.rs","zero.rs"]]],["channel.rs","context.rs","counter.rs","err.rs","lib.rs","select.rs","select_macro.rs","utils.rs","waker.rs"]],\
"crossbeam_deque":["",[],["deque.rs","lib.rs"]],\
"crossbeam_epoch":["",[["sync",[],["list.rs","mod.rs","once_lock.rs","queue.rs"]]],["atomic.rs","collector.rs","default.rs","deferred.rs","epoch.rs","guard.rs","internal.rs","lib.rs"]],\
"crossbeam_utils":["",[["atomic",[],["atomic_cell.rs","consume.rs","mod.rs","seq_lock.rs"]],["sync",[],["mod.rs","once_lock.rs","parker.rs","sharded_lock.rs","wait_group.rs"]]],["backoff.rs","cache_padded.rs","lib.rs","thread.rs"]],\
"either":["",[],["lib.rs"]],\
"exr":["",[["block",[],["chunk.rs","lines.rs","mod.rs","reader.rs","samples.rs","writer.rs"]],["compression",[["b44",[],["mod.rs","table.rs"]],["piz",[],["huffman.rs","mod.rs","wavelet.rs"]]],["mod.rs","pxr24.rs","rle.rs","zip.rs"]],["image",[["read",[],["any_channels.rs","image.rs","layers.rs","levels.rs","mod.rs","samples.rs","specific_channels.rs"]],["write",[],["channels.rs","layers.rs","mod.rs","samples.rs"]]],["crop.rs","mod.rs","pixel_vec.rs","recursive.rs"]],["meta",[],["attribute.rs","header.rs","mod.rs"]]],["error.rs","io.rs","lib.rs","math.rs"]],\
"fdeflate":["",[],["compress.rs","decompress.rs","lib.rs","tables.rs"]],\
"flate2":["",[["deflate",[],["bufread.rs","mod.rs","read.rs","write.rs"]],["ffi",[],["mod.rs","rust.rs"]],["gz",[],["bufread.rs","mod.rs","read.rs","write.rs"]],["zlib",[],["bufread.rs","mod.rs","read.rs","write.rs"]]],["bufreader.rs","crc.rs","lib.rs","mem.rs","zio.rs"]],\
"flume":["",[],["async.rs","lib.rs","select.rs","signal.rs"]],\
"futures_core":["",[["task",[["__internal",[],["atomic_waker.rs","mod.rs"]]],["mod.rs","poll.rs"]]],["future.rs","lib.rs","stream.rs"]],\
"futures_sink":["",[],["lib.rs"]],\
"getrandom":["",[],["error.rs","lib.rs","linux_android.rs","use_file.rs","util.rs","util_libc.rs"]],\
"gif":["",[["reader",[],["decoder.rs","mod.rs"]]],["common.rs","encoder.rs","lib.rs","traits.rs"]],\
"half":["",[["bfloat",[],["convert.rs"]],["binary16",[],["convert.rs"]]],["bfloat.rs","binary16.rs","leading_zeros.rs","lib.rs","slice.rs","vec.rs"]],\
"image":["",[["codecs",[["bmp",[],["decoder.rs","encoder.rs","mod.rs"]],["hdr",[],["decoder.rs","encoder.rs","mod.rs"]],["ico",[],["decoder.rs","encoder.rs","mod.rs"]],["jpeg",[],["decoder.rs","encoder.rs","entropy.rs","mod.rs","transform.rs"]],["pnm",[],["autobreak.rs","decoder.rs","encoder.rs","header.rs","mod.rs"]],["tga",[],["decoder.rs","encoder.rs","header.rs","mod.rs"]],["webp",[],["decoder.rs","encoder.rs","extended.rs","huffman.rs","loop_filter.rs","lossless.rs","lossless_transform.rs","mod.rs","transform.rs","vp8.rs"]]],["dds.rs","dxt.rs","farbfeld.rs","gif.rs","openexr.rs","png.rs","qoi.rs","tiff.rs"]],["imageops",[],["affine.rs","colorops.rs","mod.rs","sample.rs"]],["io",[],["free_functions.rs","mod.rs","reader.rs"]],["math",[],["mod.rs","rect.rs","utils.rs"]],["utils",[],["mod.rs"]]],["animation.rs","buffer.rs","color.rs","dynimage.rs","error.rs","flat.rs","image.rs","lib.rs","traits.rs"]],\
"jpeg_decoder":["",[["arch",[],["mod.rs","neon.rs","ssse3.rs"]],["decoder",[],["lossless.rs"]],["worker",[],["immediate.rs","mod.rs","multithreaded.rs","rayon.rs"]]],["decoder.rs","error.rs","huffman.rs","idct.rs","lib.rs","marker.rs","parser.rs","upsampler.rs"]],\
"lebe":["",[],["lib.rs"]],\
"libc":["",[["unix",[["linux_like",[["linux",[["arch",[["generic",[],["mod.rs"]]],["mod.rs"]],["gnu",[["b64",[["x86_64",[],["align.rs","mod.rs","not_x32.rs"]]],["mod.rs"]]],["align.rs","mod.rs"]]],["align.rs","mod.rs","non_exhaustive.rs"]]],["mod.rs"]]],["align.rs","mod.rs"]]],["fixed_width_ints.rs","lib.rs","macros.rs"]],\
"lock_api":["",[],["lib.rs","mutex.rs","remutex.rs","rwlock.rs"]],\
"memoffset":["",[],["lib.rs","offset_of.rs","raw_field.rs","span_of.rs"]],\
"miniz_oxide":["",[["deflate",[],["buffer.rs","core.rs","mod.rs","stream.rs"]],["inflate",[],["core.rs","mod.rs","output_buffer.rs","stream.rs"]]],["lib.rs","shared.rs"]],\
"nanorand":["",[["crypto",[],["chacha.rs"]],["rand",[],["chacha.rs","pcg64.rs","wyrand.rs"]]],["buffer.rs","crypto.rs","entropy.rs","gen.rs","lib.rs","rand.rs","tls.rs"]],\
"num_cpus":["",[],["lib.rs","linux.rs"]],\
"num_traits":["",[["ops",[],["bytes.rs","checked.rs","euclid.rs","inv.rs","mod.rs","mul_add.rs","overflowing.rs","saturating.rs","wrapping.rs"]]],["bounds.rs","cast.rs","float.rs","identities.rs","int.rs","lib.rs","macros.rs","pow.rs","real.rs","sign.rs"]],\
"pin_project":["",[],["lib.rs"]],\
"pin_project_internal":["",[["pin_project",[],["args.rs","attribute.rs","derive.rs","mod.rs"]]],["lib.rs","pinned_drop.rs","utils.rs"]],\
"png":["",[["decoder",[],["mod.rs","stream.rs","zlib.rs"]]],["chunk.rs","common.rs","encoder.rs","filter.rs","lib.rs","srgb.rs","text_metadata.rs","traits.rs","utils.rs"]],\
"proc_macro2":["",[],["detection.rs","extra.rs","fallback.rs","lib.rs","marker.rs","parse.rs","rcvec.rs","wrapper.rs"]],\
"qoi":["",[],["consts.rs","decode.rs","encode.rs","error.rs","header.rs","lib.rs","pixel.rs","types.rs","utils.rs"]],\
"quote":["",[],["ext.rs","format.rs","ident_fragment.rs","lib.rs","runtime.rs","spanned.rs","to_tokens.rs"]],\
"rayon":["",[["collections",[],["binary_heap.rs","btree_map.rs","btree_set.rs","hash_map.rs","hash_set.rs","linked_list.rs","mod.rs","vec_deque.rs"]],["compile_fail",[],["cannot_collect_filtermap_data.rs","cannot_zip_filtered_data.rs","cell_par_iter.rs","mod.rs","must_use.rs","no_send_par_iter.rs","rc_par_iter.rs"]],["iter",[["collect",[],["consumer.rs","mod.rs"]],["find_first_last",[],["mod.rs"]],["plumbing",[],["mod.rs"]]],["chain.rs","chunks.rs","cloned.rs","copied.rs","empty.rs","enumerate.rs","extend.rs","filter.rs","filter_map.rs","find.rs","flat_map.rs","flat_map_iter.rs","flatten.rs","flatten_iter.rs","fold.rs","fold_chunks.rs","fold_chunks_with.rs","for_each.rs","from_par_iter.rs","inspect.rs","interleave.rs","interleave_shortest.rs","intersperse.rs","len.rs","map.rs","map_with.rs","mod.rs","multizip.rs","noop.rs","once.rs","panic_fuse.rs","par_bridge.rs","positions.rs","product.rs","reduce.rs","repeat.rs","rev.rs","skip.rs","skip_any.rs","skip_any_while.rs","splitter.rs","step_by.rs","sum.rs","take.rs","take_any.rs","take_any_while.rs","try_fold.rs","try_reduce.rs","try_reduce_with.rs","unzip.rs","update.rs","while_some.rs","zip.rs","zip_eq.rs"]],["slice",[],["chunks.rs","mergesort.rs","mod.rs","quicksort.rs","rchunks.rs"]]],["array.rs","delegate.rs","lib.rs","math.rs","option.rs","par_either.rs","prelude.rs","private.rs","range.rs","range_inclusive.rs","result.rs","split_producer.rs","str.rs","string.rs","vec.rs"]],\
"rayon_core":["",[["broadcast",[],["mod.rs"]],["compile_fail",[],["mod.rs","quicksort_race1.rs","quicksort_race2.rs","quicksort_race3.rs","rc_return.rs","rc_upvar.rs","scope_join_bad.rs"]],["join",[],["mod.rs"]],["scope",[],["mod.rs"]],["sleep",[],["counters.rs","mod.rs"]],["spawn",[],["mod.rs"]],["thread_pool",[],["mod.rs"]]],["job.rs","latch.rs","lib.rs","log.rs","private.rs","registry.rs","unwind.rs"]],\
"scopeguard":["",[],["lib.rs"]],\
"simd_adler32":["",[["imp",[],["avx2.rs","avx512.rs","mod.rs","scalar.rs","sse2.rs","ssse3.rs","wasm.rs"]]],["hash.rs","lib.rs"]],\
"smallvec":["",[],["lib.rs"]],\
"spin":["",[["mutex",[],["spin.rs"]]],["barrier.rs","lazy.rs","lib.rs","mutex.rs","once.rs","relax.rs","rwlock.rs"]],\
"syn":["",[["gen",[],["clone.rs","visit_mut.rs"]]],["attr.rs","bigint.rs","buffer.rs","custom_keyword.rs","custom_punctuation.rs","data.rs","derive.rs","discouraged.rs","drops.rs","error.rs","export.rs","expr.rs","ext.rs","file.rs","gen_helper.rs","generics.rs","group.rs","ident.rs","item.rs","lib.rs","lifetime.rs","lit.rs","lookahead.rs","mac.rs","macros.rs","meta.rs","op.rs","parse.rs","parse_macro_input.rs","parse_quote.rs","pat.rs","path.rs","print.rs","punctuated.rs","restriction.rs","sealed.rs","span.rs","spanned.rs","stmt.rs","thread.rs","token.rs","ty.rs","verbatim.rs","whitespace.rs"]],\
"tiff":["",[["decoder",[],["ifd.rs","image.rs","mod.rs","stream.rs","tag_reader.rs"]],["encoder",[["compression",[],["deflate.rs","lzw.rs","mod.rs","packbits.rs","uncompressed.rs"]]],["colortype.rs","mod.rs","tiff_value.rs","writer.rs"]]],["bytecast.rs","error.rs","lib.rs","tags.rs"]],\
"unicode_ident":["",[],["lib.rs","tables.rs"]],\
"weezl":["",[],["decode.rs","encode.rs","error.rs","lib.rs"]],\
"zune_inflate":["",[["encoder",[],["fast_match_finder.rs"]]],["bitstream.rs","constants.rs","decoder.rs","encoder.rs","errors.rs","lib.rs","utils.rs"]]\
}');
createSrcSidebar();
